[package]
name    = "imugi-node"
version = "0.1.0"
edition = "2021"
 
[[bin]]
name = "imugi-node"
path = "src/main.rs"
 
[dependencies]
imugi-common       = { path = "../common" }
tokio              = { workspace = true }
tokio-rustls       = { workspace = true }
rustls             = { workspace = true }
rustls-pemfile     = { workspace = true }
anyhow             = { workspace = true }
bytes              = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
tokio-util         = { workspace = true }
futures            = { workspace = true }
uuid               = { workspace = true }
clap               = { workspace = true }
 
[target.'cfg(target_os = "linux")'.dependencies]
libc = { workspace = true }
tun  = { version = "0.6", features = ["async"] }
 
[target.'cfg(target_os = "windows")'.dependencies]
tun2        = { version = "2", features = ["async"] }
windows-sys = { version = "0.52", features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_System_SystemInformation",
    "Win32_System_WindowsProgramming",
] }